apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: myapp-namespace
  labels:
    app: myapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: kops-csi-1-21

