apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc1
  namespace: myapp-namespace
  labels:
    app: myapp
  annotations:
    meta.helm.sh/release-name: myapp
    meta.helm.sh/release-namespace: myapp-namespace
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: kops-csi-1-21
