apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: myapp-namespace
roleRef:
  kind: ClusterRole
  name: app-cluster-role
  apiGroup: rbac.authorization.k8s.io
