apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # You can give it any name; here, it's named 'jenkins-pv-access'
  # and it grants permission to list, get, and create PVs.
  # You may need to add more actions based on your use case.
  name: jenkins-pv-access
rules:
  - apiGroups:
        - ""
        - apps
        - autoscaling
        - batch
        - extensions
        - policy
        - rbac.authorization.k8s.io
    resources:
      - pods
      - secrets
      - componentstatuses
      - configmaps
      - daemonsets
      - deployments
      - events
      - endpoints
      - horizontalpodautoscalers
      - ingress
      - jobs
      - limitranges
      - namespaces
      - nodes
      - pods
      - persistentvolumes
      - persistentvolumeclaims
      - resourcequotas
      - replicasets
      - replicationcontrollers
      - serviceaccounts
      - services
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
#rules:
 # - apiGroups: [""]
  #  resources: ["persistentvolumes"]
   # verbs: ["get", "list", "create", "update", "patch", "delete"]
