apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # You can give it any name; here, it's named 'jenkins-pv-access'
  # and it grants permission to list, get, and create PVs.
  # You may need to add more actions based on your use case.
  name: jenkins-pv-access
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "create", "update", "patch", "delete"]
