replicaCount: 1

autoscaling:
  enabled: false

image1:
  repository: ganeshnelli/ultimate-cicd
  tag: 1 
  pullPolicy: IfNotPresent
image2:
  repository: ganeshnelli/test
  tag: latest
  pullPolicy: IfNotPresent

service:
  enabled: true
  name: service-1
  type: ClusterIP 
  port: 80
  targetPort: 8080
  annotations: {}

volumeMounts:
  - name: vol-1
    mountPath: /ganesh/vol

volumes:
  - name: vol-1
    persistentVolumeClaim:
      claimName: pvc1

ingress:
  enabled: true  # Change to true to enable
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []

