replicaCount: 1

autoscaling:
  enabled: false

image:
  repository: ganeshnelli/ultimate-cicd:1
  tag: latest
  pullPolicy: IfNotPresent

service:
  enabled: true
  name: service-1
  type: ClusterIP
  port: 80
  targetPort: 80
  annotations: {}

volumeMounts:
  - name: vol-1
    mountPath: /ganesh/vol  # Specify the path inside the container where the volume should be mounted

volumes:
  - name: vol-1
    persistentVolumeClaim:
      claimName: pvc1  # Replace with your actual PVC name
    # If you want to use emptyDir, you can use:
    # emptyDir: {}

